"""
Learning Models - Data structures for SEAL v2 and TabPFN

Based on Ada repo's TypeScript implementation, ported to Python with Pydantic.
"""

from typing import Dict, List, Optional, Any, Literal
from datetime import datetime
from enum import Enum
from pydantic import BaseModel, Field


class LearningStrategy(str, Enum):
    """Learning strategy based on available samples"""
    TABPFN = "tabpfn"          # < 10 samples: Few-shot learning
    HYBRID = "hybrid"          # 10-100 samples: Combined approach
    SEAL = "seal"              # > 100 samples: RL-based optimization


class ExperienceType(str, Enum):
    """Types of experiences that can be recorded"""
    BOOKING = "booking"
    PRICING = "pricing"
    COMPLIANCE = "compliance"
    MAINTENANCE = "maintenance"
    CUSTOMER_SERVICE = "customer_service"
    FRAUD_DETECTION = "fraud_detection"
    WEATHER_DECISION = "weather_decision"
    BERTH_ASSIGNMENT = "berth_assignment"


class SelfEditType(str, Enum):
    """Types of self-edits SEAL v2 can generate"""
    DATA_AUGMENTATION = "data_augmentation"
    HYPERPARAMETER_ADJUSTMENT = "hyperparameter_adjustment"
    KNOWLEDGE_RESTRUCTURING = "knowledge_restructuring"
    GRADIENT_UPDATE = "gradient_update"


class Experience(BaseModel):
    """
    Experience record for learning pipeline

    Based on Ada's ExperienceLearningPipeline.ts
    """
    experience_id: str = Field(default_factory=lambda: f"exp_{datetime.now().strftime('%Y%m%d%H%M%S%f')}")
    experience_type: ExperienceType
    timestamp: datetime = Field(default_factory=datetime.now)

    # Context data
    context: Dict[str, Any] = Field(default_factory=dict)

    # Vessel state (for maritime experiences)
    vessel_state: Optional[Dict[str, Any]] = None  # wind_speed, water_depth, speed_knots, etc.

    # Action taken
    action: str
    action_params: Dict[str, Any] = Field(default_factory=dict)

    # Outcome
    outcome: str  # "success", "failure", "partial"
    performance_score: float = Field(ge=0.0, le=1.0)  # 0-1 normalized score

    # Metrics
    metrics: Dict[str, float] = Field(default_factory=dict)

    # Learning metadata
    skill_used: Optional[str] = None
    agent_id: Optional[str] = None
    marina_id: Optional[str] = None

    # Error information (if failure)
    error: Optional[str] = None
    error_category: Optional[str] = None

    # Explicit learnings
    learnings: List[str] = Field(default_factory=list)

    class Config:
        json_schema_extra = {
            "example": {
                "experience_type": "pricing",
                "context": {"season": "high", "occupancy_rate": 0.78},
                "vessel_state": {"wind_speed": 12, "water_depth": 8.5},
                "action": "suggest_price",
                "action_params": {"suggested_price": 250, "currency": "EUR"},
                "outcome": "success",
                "performance_score": 0.95,
                "metrics": {"booking_time": 45, "customer_hesitation": 0.3},
                "skill_used": "berth_management"
            }
        }


class Prediction(BaseModel):
    """
    Prediction result from TabPFN or SEAL
    """
    prediction_id: str = Field(default_factory=lambda: f"pred_{datetime.now().strftime('%Y%m%d%H%M%S%f')}")
    timestamp: datetime = Field(default_factory=datetime.now)

    # Prediction details
    predicted_outcome: str
    confidence: float = Field(ge=0.0, le=1.0)
    probabilities: Dict[str, float] = Field(default_factory=dict)

    # Strategy used
    strategy: LearningStrategy
    sample_count: int

    # Explanation
    reasoning: Optional[str] = None
    contributing_factors: List[str] = Field(default_factory=list)

    # Cached prediction info
    from_cache: bool = False
    cache_age_seconds: Optional[float] = None


class SelfEdit(BaseModel):
    """
    Self-edit directive generated by SEAL v2

    Based on Ada's SEAL v2 self-edit generation
    """
    edit_id: str = Field(default_factory=lambda: f"edit_{datetime.now().strftime('%Y%m%d%H%M%S%f')}")
    timestamp: datetime = Field(default_factory=datetime.now)

    # Edit type
    edit_type: SelfEditType

    # Trigger analysis
    trigger: str  # What caused this self-edit
    performance_gap: float  # Gap between current and desired performance

    # Directive
    directive: str  # Human-readable explanation
    parameters: Dict[str, Any] = Field(default_factory=dict)

    # Expected impact
    expected_improvement: float = Field(ge=0.0, le=1.0)
    risk_level: Literal["low", "medium", "high"] = "low"

    # Application
    applied: bool = False
    applied_at: Optional[datetime] = None
    actual_improvement: Optional[float] = None


class Pattern(BaseModel):
    """
    Detected pattern from recurring experiences

    Based on Ada's pattern detection in ExperienceLearningPipeline.ts
    """
    pattern_id: str = Field(default_factory=lambda: f"pat_{datetime.now().strftime('%Y%m%d%H%M%S%f')}")
    timestamp: datetime = Field(default_factory=datetime.now)

    # Pattern details
    pattern_type: str
    description: str

    # Occurrence tracking
    occurrences: int = 0
    total_observations: int = 0
    frequency: float = Field(ge=0.0, le=1.0)

    # Confidence
    confidence: float = Field(ge=0.0, le=1.0)

    # Conditions
    conditions: Dict[str, Any] = Field(default_factory=dict)

    # Applicability
    applicable_contexts: List[str] = Field(default_factory=list)

    # Examples
    example_experience_ids: List[str] = Field(default_factory=list)


class SkillProgress(BaseModel):
    """
    Skill progression tracking with XP system

    Based on Ada's skill progression in ExperienceLearningPipeline.ts
    """
    skill_name: str

    # XP system
    current_xp: float = 0.0
    level: int = 1
    xp_for_next_level: float = 100.0

    # Performance tracking
    total_uses: int = 0
    successful_uses: int = 0
    failed_uses: int = 0
    success_rate: float = 0.0

    # Average performance
    average_performance: float = 0.0

    # Recent performance (last 10 uses)
    recent_performance: List[float] = Field(default_factory=list)

    # Patterns learned
    patterns_learned: List[str] = Field(default_factory=list)

    # Last used
    last_used: Optional[datetime] = None

    def calculate_success_rate(self):
        """Calculate success rate"""
        if self.total_uses == 0:
            return 0.0
        return self.successful_uses / self.total_uses

    def add_performance(self, score: float):
        """Add performance score and update metrics"""
        self.recent_performance.append(score)
        if len(self.recent_performance) > 10:
            self.recent_performance.pop(0)

        # Update average
        if self.recent_performance:
            self.average_performance = sum(self.recent_performance) / len(self.recent_performance)


class LearningStatistics(BaseModel):
    """
    Learning statistics for monitoring
    """
    # Sample counts
    total_experiences: int = 0
    experiences_by_type: Dict[ExperienceType, int] = Field(default_factory=dict)

    # Strategy usage
    tabpfn_uses: int = 0
    hybrid_uses: int = 0
    seal_uses: int = 0

    # Performance
    average_confidence: float = 0.0
    average_performance: float = 0.0

    # Self-edits
    total_self_edits: int = 0
    applied_self_edits: int = 0

    # Patterns
    total_patterns: int = 0
    high_confidence_patterns: int = 0

    # TabPFN specific
    tabpfn_cache_size: int = 0
    tabpfn_training_samples: int = 0

    # Timestamps
    last_learning_cycle: Optional[datetime] = None
    uptime_hours: float = 0.0
